describe('My First Test Suites',function()
{
it ('My First Test case',function()
{     
    cy.visit("https://1423:1423@staging-finance.rabbitinternet.com/en/product/health-insurance/questions")
    
    cy.get('#product_category > :nth-child(2) > .row > :nth-child(3) > .form-check > .form-check-label').click({force: true})
    
    cy.get('#product_accident_subcategory > :nth-child(2) > .row > :nth-child(1) > .form-check > .form-check-label').click({force: true})
    cy.get('#customer_phone > .form-group > .row > :nth-child(2) > .form-control').type('0929555842')
    cy.get('#customer_phone > :nth-child(2) > .col-12 > .btn').click()
    cy.get('#customer_first_name > .row > :nth-child(2) > .form-control').type('Ram')
    cy.get('#customer_last_name > .row > :nth-child(2) > .form-control').type('Nagar')
    cy.get(':nth-child(3) > .col-12 > .btn').click()
    cy.get('#email').type('rbl.nagar@gmail.com')
    cy.get('#customer_email > :nth-child(2) > .col-12 > .btn').click()
    cy.get('#customer_gender > :nth-child(2) > .row > :nth-child(1) > .form-check > .form-check-label').click()
    cy.get('#customer_dob > .form-group > .row > :nth-child(2) > .form-control').type('03/07/1994')
    cy.waitUntil(() =>cy.get('#customer_dob > :nth-child(2) > .col-12 > .btn').click())
    cy.get('.mx-auto > .row > :nth-child(1) > .form-check > .form-check-label').click()
    cy.waitUntil(() => cy.get('#btn-marketing-consent').click() )
    //cy.wait(4000)
    ///
    cy.waitUntil(() =>  cy.get(':nth-child(2) > .p-3 > .text-center > .SummaryCard_summary-card__block-buttons__2bIwm > :nth-child(2) > .btn:visible').click() )
    
    cy.wait(4000)
    
    cy.get('#customer_first_name > .row > :nth-child(2) > .form-control').should('have.value','Ram')   
    cy.get('#customer_last_name > .row > :nth-child(2) > .form-control').should('have.value','Nagar')      
    cy.get(':nth-child(3) > .col-12 > .btn').click()
    cy.get('#customer_phone > .form-group > .row > :nth-child(2) > .form-control').should('have.value','0929555842')  
    cy.get('#customer_phone > :nth-child(2) > .col-12 > .btn').click()
    cy.get('#email').should('have.value','rbl.nagar@gmail.com') 
    cy.get('#customer_email > :nth-child(2) > .col-12 > .btn').click()
    cy.get('#customer_nationality > :nth-child(2) > .row > :nth-child(1) > .form-check > .form-check-label').click({force: true} )
    cy.get('#customer_id_card > .row > :nth-child(2) > .form-control').type('4344444444444',{force: true})
    cy.waitUntil(() => cy.get(':nth-child(4) > .col-12 > .btn').click() )
    cy.wait(3000)
    
    cy.get('#customer_address > .row > :nth-child(2) > .form-control').type('The Line',{force: true})
    cy.get('#customer_province > :nth-child(2) > .form-control').select('Bangkok',{force: true})
    cy.get('#customer_district > :nth-child(2) > .form-control').select('Dusit')
    cy.get('#customer_subdistrict > :nth-child(2) > .form-control').select('Dusit')
    cy.get('#customer_postcode > :nth-child(2) > .form-control').select('10300')
    cy.get(':nth-child(6) > .col-12 > .btn').click()
    cy.get('#customer_billing_same > :nth-child(2) > .row > :nth-child(1) > .form-check > .form-check-label').click()
    cy.get('#customer_shipping_same > :nth-child(2) > .row > :nth-child(1) > .form-check > .form-check-label').click()
    
    cy.get('.col-lg-4 > .btn').click()
    cy.waitUntil(() => cy.get('.SummaryCard_summary-card__button__1Psp8 > .btn').click()  )
  //  cy.wait(3000)
    cy.get('#credit_card_number').type('4242424242424242')
    cy.get('#credit_card_holder_name').type('Ram Nagar')
    cy.get('#credit_card_expiry_month').select('11')
    cy.get('#credit_card_expiry_year').select('2025')
    cy.get('#credit_card_issuing_bank_country').select('THAILAND')
    cy.get('#credit_card_issuing_bank_ddl').select('AEON')
    cy.get('#cardholder_email').should('have.value','rbl.nagar@gmail.com')
    cy.get('#btnCCSubmit').click()
    cy.wait(3000)
    cy.get('.success').should('have.class','success')
    
})

})
